### ISSUE TITLE
PIE warning on App Store submission

### ISSUE THREAD

**Issue by francisjervis** [smooch/smooch-ios#103]
Hi, I am encountering a warning message when I upload a binary with Smooch (4.2.2) using xCode 7.3.
    
    WARNING ITMS-90080: "The executable 'Payload/TimesFree.app/Frameworks/Smooch.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information refer to Technical Q&A QA1788 - Building a Position Independent Executable in the iOS Developer Library."

I have followed the instructions at 
https://developer.apple.com/library/ios/qa/qa1788/_index.html
and verified that all the "Generate position-dependent executable" flags are set to NO at the project/target level.

**Comment by mspensieri** [comment]
Thanks for the report, but it seems this issue is not specific to Smooch.

The Smooch framework is indeed built with both required flags set to `NO`, but apparently validation has changed a bit on Apple's side and is causing this issue to appear for many popular frameworks. It seems to be attributed to a bug in the iTunes Connect validation process.

See [this thread](https://github.com/CocoaPods/CocoaPods/issues/5453) for more information, specifically [this comment](https://github.com/CocoaPods/CocoaPods/issues/5453#issuecomment-223631754)
