### ISSUE TITLE
Smooch + Zendesk = New ticket

### ISSUE THREAD

**Issue by dunice** [smooch/smooch-ios#108]
Hi guys,

Is there a way to create a new ticket at Zendesk when the latest is already closed?

ps.: I think the title for this issue isn't good enough, but I didn't find a better one! :)

**Comment by mspensieri** [comment]
This is supposed to be the default behaviour - when a ticket is "Closed" in Zendesk, it can no longer be re-opened by any means, so Smooch will create a new one. When a ticket is "Solved", however, Smooch will attempt to reuse that existing ticket.

If this isn't what you're seeing, please send an email to help@smooch.io and we'll be happy to look into it :)

Closing this issue since it's not related to the iOS SDK
