### ISSUE TITLE
iOS does not receive push notification if outside of the app.

### ISSUE THREAD

**Issue by SupreeSeekSter** [smooch/smooch-ios#121]
I receive push notification only if I open my app. I uploaded the .p12 file.

Is there anything else I need to do?

My iOS version is 10.2

**Comment by mspensieri** [comment]
Can you check the alerts icon in the top right of the [Smooch dashboard](https://app.smooch.io/) to see if there are any errors?

![screen shot 2016-12-20 at 12 58 01 pm](https://cloud.githubusercontent.com/assets/2286852/21361902/0c062678-c6b4-11e6-8cbd-74c3930adf15.png)

**Comment by clayellis** [comment]
@mspensieri The tutorial [here](https://docs.smooch.io/guide/native-ios-sdk/) doesn't list anything about `UIApplication.registerForRemoteNotifications(_:)` (and related delegate methods.) I'm not super experienced in push notifications so I'm not sure if that strategy is necessary when using .p12 files.

**Comment by mspensieri** [comment]
API calls like `UIApplication.registerForRemoteNotifications`, `UNUserNotificationCenter.requestAuthorizationWithOptions`, and `UIApplication.registerUserNotificationSettings` are called automatically by the Smooch SDK, unless you specify otherwise on your `SKTSettings` object.

We have flags to disable auto registration, namely [`enableAppDelegateSwizzling`](https://docs.smooch.io/api/ios/Classes/SKTSettings.html#//api/name/enableAppDelegateSwizzling) and [`requestPushPermissionOnFirstMessage`](https://docs.smooch.io/api/ios/Classes/SKTSettings.html#//api/name/requestPushPermissionOnFirstMessage), but the default value of those flags is `true`, so it shouldn't be necessary to call those yourself in most cases

**Comment by clayellis** [comment]
@mspensieri Good to know! Thanks for always being so responsive (and helpful!)

**Comment by abadikaka** [comment]
hi i am also has same issue , do we need at least to smooch init in appdelegate ?
@mspensieri 

i init my smooch on Swift class, and call smooch chat from obj-c bridging, but every smooch func like login, logout, init is in swift class...
then the notif only come whenever the app is open, if in background or i dont open the app wouldnt get the notifications.. then i open the app, will be suddenly receive the notifications

**Comment by wmora** [comment]
Hey @abadikaka are you still having this issue?

**Comment by wmora** [comment]
Closing this now, @abadikaka please open a separate issue if you're still having issues with push notifications
