### ISSUE TITLE
How to send a message to our customer initiated by us via slack and/or front?

### ISSUE THREAD

**Issue by qadirsuh** [smooch/smooch-ios#129]
let say we have a customer using our iOS app (smooch iOS SDK is integrated) but he/she didn't sent a message via smooch chat widget. Is there any way to know that new customer has started using our app, so that we can start conversation with them by sending his/her a message saying greetings

basically the question is How to send a message (smooch) to our customer initiated by us via slack and/or front?

**Comment by wmora** [comment]
Hey there, 

You can use a Whisper to start a conversation with a user with a welcome message upon launching your app for the first time. See the [docs](https://docs.smooch.io/faq/whispers/) for more detail.

**Comment by qadirsuh** [comment]
@wmora yes I know I can send the greetings via whisper on app launch. but this will not create any new channel in slack/Front app (unless customer send a reply message). I need to start the conversation from business end. So that I can send as many messages as I want.

**Comment by mspensieri** [comment]
There are two ways you can accomplish this
1. You can use the API to send messages to the user, instead of using Slack or Front, but that doesn't directly answer your question. Messages sent in this way will _also_ not open a channel in Slack.
2. You can send a message on behalf of the user using the Smooch [`sendMessage:`](https://docs.smooch.io/api/ios/Classes/SKTConversation.html#//api/name/sendMessage:) API, and that will open a conversation in Slack/Front that you can use to reply

**Comment by qadirsuh** [comment]
Wow! @mspensieri thanks for mentioning the solution 2. this is gonna work in my case.

**Comment by qadirsuh** [comment]
Thanks for solution again @mspensieri its worked. but I want to not render that Message in chat conversation. can we control this in any way? which I have sent via [sendMessage:](https://docs.smooch.io/api/ios/Classes/SKTConversation.html#//api/name/sendMessage:) api. Hope not?

**Comment by mspensieri** [comment]
There isn't a way to hide unwanted messages unfortunately. The view will display whatever is in the history, and using the `sendMessage` API will always add a message to the history.
