### ISSUE TITLE
Adding a toolbar with "Done" button?

### ISSUE THREAD

**Issue by marbetschar** [smooch/smooch-ios#130]
I'm experiencing issues with the text input moving too far up - even with latest version `5.4.5` as described here: https://github.com/smooch/smooch-ios/issues/123

I would prefer to add a toolbar below the text input field with a "Done" button.

Because we got a lot of feedback from users which do not know how to finish the chat and return to the other functionalities of our app (see attached screenshot - there is a white space between keyboard and text input, exactly there I'd like to add the toolbar).

How is this possible?

![simulator screen shot 04 02 2017 14 57 11](https://cloud.githubusercontent.com/assets/392542/22619010/46ea4336-eaeb-11e6-90ad-a1a00dccbaea.png)

**Comment by mspensieri** [comment]
With regards to the placement issue (#123), I was still waiting on a sample project reproducing the issue, since I wasn't able to reproduce it on my side. If you have the time maybe you could provide one?

About the toolbar with `Done` button, unfortunately I can't think of a way to support that use case with the way the conversation view is currently implemented. I'll flag this issue as an enhancement and bring the feature request to the team for discussion.

Note that if the conversation view is displayed in a container _other_ than a `UITabBarController`, the `Done` button will appear in the navigation bar in the top-left of the view

**Comment by marbetschar** [comment]
@mspensieri I'll see if i can put together a sample project in the next few days.

Don't know about the internal specifics of the conversation view, but [adding a toolbar as `inputAccessoryView` to the `UITextField`](http://stackoverflow.com/questions/23904848/how-to-add-toolbar-above-keyboard) should do the job?

**Comment by mspensieri** [comment]
What I meant was I can't think of a way for _you_ to add this toolbar using the current version of the SDK. It would require code changes on our side, hence why I've tagged it as a feature request

**Comment by marbetschar** [comment]
Any news or progress on this issue? Hitting this wall regularly with our clients, so it would be awesome to add this `Done` button so they know how to close the keyboard.

**Comment by jpjoyal** [comment]
@marbetschar We've added this to our enhancement queue but its ranked low since this enhancement applies to UITabBarController users only. We'll update this thread once fixed.

**Comment by wmora** [comment]
We added a 'Done' to dismiss the keyboard when the view is presented as part of a tabbar controller in version [5.6.2](https://github.com/smooch/smooch-ios/releases/tag/5.6.2)
