### ISSUE TITLE
postMessage api calling via alamofire

### ISSUE THREAD

**Issue by qadirsuh** [smooch/smooch-ios#131]
I am trying to post a message using postMessage REST api of smooch as a role appMaker.
I have done like below.

```      
let payloads:[String: Any] = ["scope": "app"]
        let jwt =  JWT.encode(payloads, algorithm: .hs256("XXXX-my-smooch-key-id-XXXXX".data(using: String.Encoding.utf8)!))
       
        let smoochPostMessageUrl = "https://api.smooch.io/v1/appusers/\(smoochUserID)/messages/";
        let headers = ["Content-Type" : "application/json", "app-token" : smoochAppToken];
        let params:[String: Any] = [
            "text": userMessage,
            "role": "appMaker",
            "authorization": "Bearer \(jwt)"
        ]
        
        Alamofire.request(smoochPostMessageUrl, method: .post, parameters: params, encoding: JSONEncoding.default, headers: headers).responseJSON { (response:DataResponse<Any>) in
            
            switch(response.result) {
            case .success(_):
                if let data = response.result.value{
                    
                    print("SUCCESS")
                    print(response.result.value) 
                    
                }
                break
                
            case .failure(_):
                
                print("FAILURE")
                print(response.result.error)
                
                break
                
            }
        }
```

I am getting following response

`Optional({
    error =     {
        code = forbidden;
        description = "Adding an appMaker message requires one of the following JWT scopes: app, integration, account";
    };
})`

What I am missing here.

**Comment by qadirsuh** [comment]
I have used [JSONWebToken.swift)](https://github.com/kylef/JSONWebToken.swift) to generate my JWT

**Comment by mspensieri** [comment]
Let me first preface this answer by saying that:

1. JWTs should **never** be signed on the end-user's device. Passing your key pair down to the user's device  for JWT creation (or hardcoding those values in your application) is a big security risk, as it gives every user of your application the ability to act on behalf of the account owner. They can manage integrations, webhooks, view other users' conversations, etc. If your server is written in Swift, then continue reading, otherwise I would advise you not to continue further on this path.
2. You should also never pass down a JWT with a scope other than `appUser` to a user's device. JWTs with scope other than `appUser` should only be used for server-to-server calls, for the reasons outlined in point 1.

That being said, I'll try to answer your question anyways. There are a few problems with this code, the first and most obvious being that the JWT lib you linked does not support custom [JWT Header](http://self-issued.info/docs/draft-jones-json-web-token-01.html#anchor5) fields (see [here](https://github.com/kylef/JSONWebToken.swift/blob/master/Sources/Encode.swift#L17)). Smooch requires a `kid` field in the JWT header to specify the id of the key pair used for signing the request. A typical Smooch JWT header looks like this:

```json
{
  "typ": "JWT",
  "alg": "HS256",
  "kid": "app_569e627605997064b94248d3"
}
```

The second issue with the code is that you're passing the `authorization` field in the body of your request, rather than in an HTTP header. The code should instead be:

```swift
let headers = ["Content-Type" : "application/json", "app-token" : smoochAppToken, "Authorization": "Bearer \(jwt)"];
let params:[String: Any] = [
    "text": userMessage,
    "role": "appMaker"
]
```

I'm also not sure about the way you are generating the JWT signature. Your placeholder code shows `XXXX-my-smooch-key-id-XXXXX` is used as the credential, when in fact it should be your Smooch key *secret*, not your key *id*. It's possible you're using the right value anyways, I just wanted to point that out
