### ISSUE TITLE
Server side messages not displaying for new conversations

### ISSUE THREAD

**Issue by alexfish** [smooch/smooch-ios#138]
**Steps:**

1. New user starts new converstation
2. Send message via `https://meya.ai` to the user
3. Expect to see message
4. Message is not displayed until the user inputs or quits the app and re-opens chat.

**Description:**

Seems the view is not reloaded when messages are received from the server for new conversations. User sending a message seems to trigger the refresh as the server side messages then appear.

**Comment by wmora** [comment]
That is the intended behavior. When a user is first created from the SDK, the conversation will not listen for server messages until they send a message to the business. Once a user is created, subsequent app launches will also check for messages from the business to start listening for server messages.

**Comment by alexfish** [comment]
that's a shame, our setup is that we have links from our support view in app that can trigger flows inside of Smooch chat.

e.g:

1. User selects `send to a friend` inside support
2. Opens Smooch with message from chat bot around sending to a friend and options

Is our only solution to send a message from the user to trigger the Smooch listener? we were trying to avoid sending messages from the user that they didn't type for UX reasons.

**Comment by mspensieri** [comment]
You could use [Whispers](https://docs.smooch.io/guide/automated-messages/) to reach out automatically to the user, rather than sending the initial message via the REST API.

Otherwise, a push notification to the user's device from Smooch (we send one on each message) should trigger the application to fetch the message history. Are you testing on a push-enabled device?

**Comment by alexfish** [comment]
ok thanks, we'll try the push route
