### ISSUE TITLE
Not Receiving Previous Messages

### ISSUE THREAD

**Issue by hcrub** [smooch/smooch-ios#154]
Not receiving previous messages from `SKTConversation`.

**Versions**
5.5.0 - 5.6.6

**Description**
We immediately setup Smooch then load all of the previous message history. Looks something like:
```objc
// Setup
SKTSettings *settings = [SKTSettings settingsWithAppToken:@"TOKEN"];
settings.userId = @"TEST_USER";
[Smooch initWithSettings:settings];
[Smooch conversation].delegate = self;

// Load history
[[Smooch conversation] loadPreviousMessages];
```
Up until a few days ago, `SKTConversationDelegate`'s `conversation:didReceivePreviousMessages:` is no longer getting called with the previous message history at no point throughout the application's lifecycle nor subsequent launches.

**Reproducing**

1.) Download the test project [here](https://github.com/hcrub/SmoochTesting).
2.) Place your token in `ViewController.m`.
3.) Create a new Whisper (e.g. `test_trigger`).
4.) Run the application once.
> Each run will trigger a test Whisper and send a message on behalf of a test user. We should now have two messages (1 inbound, 1 outbound) in the Smooch logs.

5.) Run the application again. 
> `conversation:didReceivePreviousMessages:` is never called. Also, `[Smooch conversation].previous` is `nil`.

**Comment by mspensieri** [comment]
Hey @hcrub, thanks for the report, though I think you might be misunderstanding the purpose of `loadPreviousMessages`. 

When you call `initWithSettings`, the Smooch SDK will automatically fetch the most recent page of messages (latest 100 messages) as part of the initialization process. `loadPreviousMessages` is used when the user has an existing conversation history that is *longer* than the message page size (100 messages), i.e. when `[Smooch conversation].previous` exists, and you want to fetch more history.

In the default Smooch UI, `loadPreviousMessages` is called when the user scrolls all to the way to the top of the conversation view, to fetch the previous page of messages, if it exists. In your example the conversation only has 2 messages, so there is no previous page to fetch, so `loadPreviousMessages` is a no-op.

I believe the fact that `conversation:didReceivePreviousMessages:` was called on app startup for versions prior to v5.5.0 was a bug, and was not actually communicating anything valuable.

Can you explain a bit more what you were using this notification for? Why are you calling `loadPreviousMessages` at app launch time?

**Comment by hcrub** [comment]
Gotcha. I ported this subset of code from our active project of which we're migrating from the default Smooch UI to our own custom implementation. I had assumed we were required to call `loadPreviousMessages` to fetch the full/partial message history _(that's why it's called immediately)_ but I see that these are available in `messages`.

Is the previous message history _(<100)_ synchronously or asynchronously available in `messages`? For instance, in my case, I want to access them immediately after I initialize the SDK via `+initWithSettings:`. Is that safe to do?

**Comment by mspensieri** [comment]
The conversation history is synchronously loaded from disk, and asynchronously loaded from the server, so accessing `messages` directly after init _will_ return messages, but it will be a cached version of the history from the previous launch of the app.

You can listen to [`conversation:didReceiveMessages:`](https://docs.smooch.io/api/ios/Protocols/SKTConversationDelegate.html#//api/name/conversation:didReceiveMessages:) to be notified if anything new was found during the initial asynchronous fetch from the server (and of course when any other messages are received during the lifetime of the app).

**Comment by hcrub** [comment]
That'll work just fine. Thanks for the quick help!

**Comment by abadikaka** [comment]
hi guys @mspensieri or @hcrub or @wmora  . i have problem dealing with messages . I dunno if u guys know what is my mistake on my logic for retrieve the latest message. i will write my code here.

I have an array of apptoken and since now smooch on ios has destroy function i am able to initiate smooch on different apptoken on runtime and i can chat to each token smoothly..

but then, i am trying to retrieve each last message to be displayed on my mobile message screen ( like other app that has messages feature ). I am sure we can do this by using last message properties from SMooch SDK by access the SKTConversation and SKTMessage..
but in every first time i call the function it always return empty . only on first call. then i refresh again the function i get the message list. It also happen if i have 4 kind of apptoken, i need refresh 4 times to get all of the message history..

```

@objc public func getConversationsList(array: [String], userID: String) -> String?{
        var activearray = Array<Any>()
        var inactivearray = Array<Any>()
        var allarray = Array<Any>()
        var okkamidict = [String: Any]()
        var counter = 0
        for data in array {
            Smooch.destroy()
            Smooch.initWith(SKTSettings(appToken: array[counter]))
            Smooch.login(userID, jwt: nil)
            var listMessage : [Any?] = (Smooch.conversation()?.messages)!
            let unreadMsgCount = Smooch.conversation()?.unreadCount

            //no message, skip
             if listMessage.count == 0{
                continue
            }
            var iconUrl = ""
            var channelName = ""
            for msg in listMessage {
                let msgSkt = msg as! SKTMessage
                if (!msgSkt.isFromCurrentUser) {
                    iconUrl = (msg as! SKTMessage).avatarUrl!
                    channelName = (msg as! SKTMessage).name!
                    break
                }
            }
            let lastMsg : SKTMessage = listMessage[listMessage.count - 1] as! SKTMessage
            let lastMsgText : String? = lastMsg.text
            
            let epTime : Date = lastMsg.date!
            let dateFormatter = DateFormatter()
            dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
            let dateString = dateFormatter.string(from:epTime)
            
            let dateComponentsFormatter = DateComponentsFormatter()
            dateComponentsFormatter.allowedUnits = [.year,.month,.weekOfYear,.day,.hour,.minute,.second]
            dateComponentsFormatter.maximumUnitCount = 1
            dateComponentsFormatter.unitsStyle = .full
            dateComponentsFormatter.string(from: Date(), to: epTime)
            
            var dict = [String: Any]()
            var msg = "Sent You Something"
            if(lastMsgText != nil){
                msg = lastMsgText!
            }
            
            dict = ["unread_messages":unreadMsgCount! as UInt,"icon":iconUrl,"channel_name":channelName,"last_message":msg,"time_since_last_message":dateComponentsFormatter.string(from: epTime, to: Date())!,"app_token":array[counter],"last_time":dateString]
            if counter == 0 {//put all
                allarray.append(dict)
            }else if counter > 0 && unreadMsgCount! > 0{// add active
                activearray.append(dict)
            }else{//add unactive
                inactivearray.append(dict)
            }
            counter += 1
        }
        
        okkamidict["ALL_CHAT"] = allarray
        okkamidict["ACTIVE_CHATS"] = activearray
        okkamidict["INACTIVE_CHATS"] = inactivearray
        
        print("Dict : ", okkamidict)
        do {
            let data = try JSONSerialization.data(withJSONObject:okkamidict, options: JSONSerialization.WritingOptions.prettyPrinted)
            let str = String(data:data, encoding: String.Encoding.utf8)
            return str!
        } catch {
            print("JSON error")
            return nil
        }
    }
```

Test case : 
1. i have array of 4 apptoken..
2. i call getConversationList function, it return null for all apptoken messages
3. i call again the function, it return history of 1 apptoken (first index), 3 apptoken null,
4. i call again, it return history of 2 apptoken (first and second index)
5. repeat until i can get the whole message

^this test case only happen on first time fresh sign in user..
i am thinking of only one time call i can get all of the message history and take the latest messages. Am i able to do that with Smooch .?  thanks..

**Comment by mspensieri** [comment]
@abadikaka off the bat I notice that your counter is not incremented in the case where no messages are found, so you probably end up checking the same conversation 4 times:

```
if listMessage.count == 0 {
  continue
}
```

But as for the whole thing, the SDK wasn't really designed to be able to switch app tokens rapidly in a loop like this - there's a lot of async work that happens when you call `initWithSettings:` or `login:jwt:`. Unfortunately I can't really help you debug this issue since the SDK isn't intended to work this way, so I can't guarantee it would even work with my help. I wouldn't be surprised if you got unexpected crashes or undefined behaviour running a loop like this

**Comment by abadikaka** [comment]
Yeah i notice that too that i believe lot of async work inside of it. Ok thanks at least i know how the sdk work from your explanation.. i will try my best first.. thank u so much @mspensieri..
