### ISSUE TITLE
Using the camera crashes the app

### ISSUE THREAD

**Issue by maleksiuk** [smooch/smooch-ios#187]
Hi there,

Using the 'Take Photo' functionality of the app causes a crash when the user has given permission to use the camera but has not given permission to use the photo library (either because they have not been asked or because they have been asked but denied permission).

Reproduced on an iPhone 8+ running iOS 11.2.1.  Was not able to reproduce on our iPhone SE running iOS 10.3.2

It crashed on both Smooch 6.6.1 and Smooch 6.2.1

Steps to reproduce:
 * create an iOS app with Smooch installed and with the keys NSCameraUsageDescription and NSPhotoLibraryUsageDescription set in the Info plist
 * open the Smooch window
 * tap the camera icon and then 'Take Photo'
 * take a photo and tap 'Use Photo'
 * a crash occurs

Here's a stack trace:

```
libsystem_kernel.dylib | abort_with_payload (libsystem_kernel.dylib)
TCC | __CRASHING_DUE_TO_PRIVACY_VIOLATION__ (TCC)
TCC | __TCCAccessRequest_block_invoke.77 (TCC)
TCC | __tccd_send_block_invoke (TCC)
libxpc.dylib | _xpc_connection_reply_callout (libxpc.dylib)
libxpc.dylib | _xpc_connection_call_reply_async (libxpc.dylib)
libdispatch.dylib | _dispatch_client_callout3 (libdispatch.dylib)
libdispatch.dylib | _dispatch_mach_msg_async_reply_invoke$VARIANT$armv81 (libdispatch.dylib)
libdispatch.dylib | _dispatch_queue_override_invoke$VARIANT$armv81 (libdispatch.dylib)
libdispatch.dylib | _dispatch_root_queue_drain (libdispatch.dylib)
libdispatch.dylib | _dispatch_worker_thread3 (libdispatch.dylib)
libsystem_pthread.dylib | _pthread_wqthread (libsystem_pthread.dylib)
libsystem_pthread.dylib | start_wqthread (libsystem_pthread.dylib)
```

Thanks!

**Comment by mspensieri** [comment]
Thanks for the details, we'll look into it!

**Comment by wmora** [comment]
The crash happens because the key [NSPhotoLibraryAddUsageDescription](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW73) is required starting on iOS 11. You'll need to provide a value for this key in your app's Info.plist. Version [6.7.0](https://github.com/smooch/smooch-ios/releases/tag/6.7.0) of the SDK will detect if the value is present before displaying the option to take a picture, otherwise the option will be hidden. Thanks for reporting!
