### ISSUE TITLE
Only receiving notifications when app is foregrounded

### ISSUE THREAD

**Issue by Leeds-eBooks** [smooch/smooch-ios#197]
Apologies for the duplicate issue (#121), but the response there was "please open a separate issue if you're still having issues with push notifications" so that's what I'm doing.

My p12 certificate expired, so I generated a new one from the Apple dev center and uploaded it to app.smooch.io

Notifications are now working again, but only when the app is in the foreground. This was not the case before my certificate expired. There is no error alert in my Smooch dashboard.

Have I done something wrong, or is this a bug? I don't know if it is relevant, but I recently created one of the new Apple app keys to replace my expired APNs certificate for Firebase notifications. That was before I created this renewed p12 for Smooch. (Incidentally, it would be brilliant if Smooch could move over to using this key, as it will never expire, so we won't have to renew our certificate every year!)

Thanks very much for any help you can give!

**Comment by mspensieri** [comment]
There are a couple things to check to see where your push notif might be failing. If you navigate to the iOS integration page on the Smooch dashboard, you can verify that the mode of your certificate (Production or Development) matches the app you are testing against. For apps built and pushed through XCode, you will need to use a Development certificate. If your app is distributed through the app store, a Production certificate should be used.

You can also check the "Last push notification attempted" flag to see if the push was actually attempted or not. If the push was attempted and does not show up on the device, it's likely a configuration issue.

![screen shot 2018-07-03 at 9 28 15 am](https://user-images.githubusercontent.com/2286852/42222614-b1e8d04c-7ea3-11e8-9d5f-21f3d2a74c21.png)

Please also be aware that the comment you are referring to from #121 is from May of last year, and our processes have changed a bit since then. GitHub issues in this repository are reserved for bug reports related to the functionality of the SDK itself, and not issues related to the backend/configuration. If you contact our customer success team, someone with more information about your account and your specific config should be able to help you work through this problem!

**Comment by brenoxp** [comment]
I'm having this same issue. I followed the tutorial, disabled the swizzling mode, implemented the required calls on designed delegates methods on AppDelegate. 

- Development .p12 file on iOS configuration on dashboard, running through XCode.
- "Last push notification attempted a few seconds ago"
- Calling Smooch.login, with success result

After these steps I can send messages while the app is open. When the app is closed I can only see the received messages after open the app. If, and only if, I send a message with the user that's not receiving the messages this user will receive the push notifications on the background.

On the Logs page on the dashboard I can see calls to the api, but no tries of sending iOS Messaging. After the user sends a message, I can see logs tries of sending iOS Messaging.

**Comment by vaibhav-jhaveri-ds** [comment]
@brenoxp @benadamstyles Did you find any solution or information on this issue? I'm facing the same behavior regarding receiving notifications only when App is in Foreground

**Comment by brenoxp** [comment]
I had to send a message from the user account to me every time the user was login in.

**Comment by vaibhav-jhaveri-ds** [comment]
@brenoxp Means?

**Comment by brenoxp** [comment]
Look like Smooch only works well when the user has a problem and contact the company, and because of that only when the user sends the first message the access token of the phone is sent. So on the first login of the user on a new installation of the app I have to send a message through Smooch manually, something like "{username} logged in" and for that you can use.

`Smooch.conversation()?.sendMessage(SKTMessage(text: message))`

After you do that you can send messages to the user and he will receive push notifications with the app closed or on background.

**Comment by vaibhav-jhaveri-ds** [comment]
@brenoxp Okay, I'll try that
