### ISSUE TITLE
Remote notification delegates getting called after Smooch init

### ISSUE THREAD

**Issue by modastic** [smooch/smooch-ios#67]
In version 3.2.2, the delegate method, 
application:didRegisterForRemoteNotificationsWithDeviceToken: 
gets called every time after smooch init and after calling smooch login. I tried disabling enableAppDelegateSwizzling but it doesn't seem to do anything. The delegate method is getting called even before we prompted the user for push notifications. This doesn't happen in version 3.0.1

**Comment by mspensieri** [comment]
Starting in v3.1.0 or v3.1.1 (can't remember exactly) we added a call to `[[UIApplication sharedApplication] registerForRemoteNotifications]` to ensure that all Smooch users have an up-to-date device token in our backend (assuming you've uploaded a certificate in the Smooch web app). This call only registers for _silent_ push notifications, and won't prompt for user notification privileges - your app can still choose when and how to display that prompt.

Is the callback causing incorrect behavior in your app?

**Comment by modastic** [comment]
Yes the callback is causing incorrect behaviour for us because we're not expecting it to be called before we prompt the user for push notifications.

**Comment by mspensieri** [comment]
Can you give a bit more context as to what exactly is going wrong?

Would it be sufficient to add a check for current user notification settings in your deviceToken callback?

```objc
-(void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
    if([[UIApplication sharedApplication] currentUserNotificationSettings].types == UIUserNotificationTypeNone){
        return;
    }
    
    // Do whatever
}
```

**Comment by modastic** [comment]
That works but it just seems weird to have to do that.

**Comment by DarrylBayliss** [comment]
I noticed this behaviour as well whilst doing some debugging.

It feels wrong application:didRegisterForRemoteNotificationsWithDeviceToken: is being called with a device token because I would expect the user to have explicitly enabled push notifications in the app before this occurs. I don't think whether it is a silent notification or otherwise should make a difference.

**Comment by mspensieri** [comment]
I'll give some more details here. For certain use cases, Smooch requires a push notification token _before_ the user has granted permission to receive alerts, because we use push as a mechanism to notify the client of a change in state (considered valid usage per Apple guidelines). One such use case is as follows:

1. The user launches the app for the first time, and has a `conversationStarted` value of `false. This means our SDK is not connected to websockets and is not listening for new messages.
2. Your application uses custom code on the backend side to invoke the Smooch REST API and initiate a conversation with a user in response to some action.
3. Smooch sends a push notification to the user's device, signalling the SDK that a conversation has been started remotely. The SDK then requests the conversation data from our server, and displays the message to the user.

In step 2, the reason for using the REST API instead of Whispers is because either the logic for initiating a conversation, or the specifics of the message composition, surpass the capabilities of our Whispers feature.

I'm open to suggestions on alternative SDK behaviour that supports at least the above use case, but for the moment we won't be changing this behaviour as many of our integrators actually depend on it to reliably initiate a conversation with a specific user.
