### ISSUE TITLE
Minor issue - reporting 3.5.4 as the 'latest' version in console output. 

### ISSUE THREAD

**Issue by gemmakbarlow** [smooch/smooch-ios#83]
Just upgraded the Smooch pod and upgraded to receive this message in the console:

<pre>
2016-03-01 14:36:08.945 Harry's[49729:1800642] There is a new Smooch version available. You have 4.0.1, version 3.5.4 is available. Visit https://github.com/smooch/smooch-ios to download it or do a 'pod update'
</pre>

Noticed this occurring once before - something you can fix server-side?

**Comment by mspensieri** [comment]
The check is actually done device-side (simulator only), and it finds the latest release by sorting by `published_at`... I think I created the `4.0.1` release a couple minutes before the `3.5.4` release, so the SDK is probably treating that one as newer... Not sure what can be done about this, might just have to wait until `4.0.2`, otherwise I would need to re-release v4.0.1

Regardless, the check is pretty harmless and shouldn't even run on a physical device.

**Comment by gemmakbarlow** [comment]
Agree - totally harmless, just wanted to let you know that this has happened a couple of times. 

I'd personally wait until 4.0.2.

**Comment by mspensieri** [comment]
Sorry about the annoyance :P Thanks for the heads up though!
