### ISSUE TITLE
Emojis don't transmit back from Slack to smooch

### ISSUE THREAD

**Issue by vondiplo** [smooch/smooch-ios#97]
![image](https://cloud.githubusercontent.com/assets/1870445/14768946/c4c59e8e-0a56-11e6-9e7d-3aa1ad03c6ff.jpg)

**Comment by mspensieri** [comment]
This is a known limitation of the Slack integration, and it's because Slack doesn't use unicode characters to represent emojis. This issue is tracked internally as well as here https://github.com/smooch/smooch-android/issues/5. I'll close this issue since it's not specifically related to the iOS SDK, but rest assured it's being tracked on our side :)
