### ISSUE TITLE
Crash in [__NSCFString onMessagesChanged:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by mgurkivskyi** [smooch/smooch-ios#98]
I've receive notification about crash in smooch-ios, detailed info: http://crashes.to/s/5a84632cacd
Smooch version - 4.1.2

**Comment by mspensieri** [comment]
Thanks for the report @mgurkivskyi. From the stack trace it looks like this is the flow of events:

1. New messages comes in to Smooch
2. Smooch fires `SKTConversationDidReceiveMessagesNotification`
3. `NSNotificationCenter` has a listener registered for that notification, with the target object being of type `NSString` and the target selector being `onMessagesChanged:`
4. Crash happens because `NSString` doesnt respond to `onMessagesChanged:` (obviously)

We do have one place in our code where `onMessagesChanged:` is a valid selector, but it definitely should not be invoked on an instance of `NSString`! Before I jump down a rabbit hole trying to figure out how this could occur, can you please validate that the same selector isn't being used somewhere in your code with an invalid target?

**Comment by mspensieri** [comment]
Fix has been made in [v4.2.1](https://github.com/smooch/smooch-ios/releases/tag/4.2.1), please reopen if it still occurs
