### ISSUE TITLE
Slack channel archiving not taking effect after set time limit

### ISSUE THREAD

**Issue by soedr** [smooch/smooch-ios#99]
I've set the time limit for automatic channel archiving in slack on the integration settings page at smooch.io, but the channel is not archived - how does one fix this?

**Comment by mspensieri** [comment]
If auto-archiving isn't working, make sure that the account you used to integrate Slack has the "Archive a Channel" permission (https://get.slack.help/hc/en-us/articles/201314026-Roles-and-permissions-in-Slack).

If you do have the correct permission, and auto-archiving is enabled, but still not working, please [contact support](https://smooch.io/help/) and they'll gladly help you out :)

Closing this issue since it's not related to the iOS SDK
